on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1-16/8 * * *'
  workflow_dispatch:  
permissions:
  contents: write

name: update free subscriptions
jobs:
  update_subscriptions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: "26.1.4"
          channel: test
      - run: docker version
      - run: docker info
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: update subscriptions
        run: node fetch_subscriptions.js ${{ secrets.xboard_api_secret }} ${{ secrets.xboard_api_url }}
      - name: Deploy crashgfw free-node-store
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'dest' 
          repository-name: crashgfw/free-node-store
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          commit-message: "Update free subscription links"
      - name: update readme files
        run: node generate_markdown2.js ${{ secrets.xboard_api_secret }} ${{ secrets.xboard_api_url }}
      - name: Deploy crashgfw free-airport-nodes
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'dest2'
          branch: 'main'
          repository-name: crashgfw/free-airport-nodes
          ssh-key: ${{ secrets.DEPLOY_KEY2 }}
          commit-message: "Update free subscription links"
      - name: update free-proxy-nodes/free-nodes readme files
        run: node generate_markdown3.js ${{ secrets.xboard_api_secret }} ${{ secrets.xboard_api_url }}
      - name: Deploy free-proxy-nodes/free-nodes
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'dest3'
          branch: 'main'
          repository-name: free-proxy-nodes/free-nodes
          ssh-key: ${{ secrets.DEPLOY_KEY3 }}
          commit-message: "Update free subscription links"
      - name: update hiddifyapp350 readme files 
        run: node generate_markdown4.js ${{ secrets.xboard_api_secret }} ${{ secrets.xboard_api_url }}
      - name: Deploy free-proxy-nodes/free-nodes
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'dest4'
          branch: 'main'
          repository-name: hiddifyapp350/free-nodes
          ssh-key: ${{ secrets.DEPLOY_KEY4 }}
          commit-message: "Update free subscription links"


